<?php

namespace ILIAS\Plugin\LongEssayAssessment\UI\Table\Column;

use ILIAS\Language\Language;
use ILIAS\UI\Implementation\Component\Table\Column\Boolean;

class NullableBool extends Boolean
{
    public function __construct(Language $lng, string $title)
    {

        $yes = $lng->txt('yes');
        $no = $lng->txt('no');

        parent::__construct($lng, $title, $yes, $no);
    }

    public function format($value): string
    {
        if ($value === null) {
            return "";
        }
        return parent::format($value); // TODO: Change the autogenerated stub
    }

}
