<?php

namespace ILIAS\Plugin\LongEssayAssessment\UI\Table\Column;

use ILIAS\UI\Implementation\Component\Table\Column\Number;

class NullableNumber extends Number
{
    public function format($value): string
    {
        if($value === null) {
            return "";
        }
        return parent::format($value); // TODO: Change the autogenerated stub
    }

}