export default {
    "settingsHeadings": "Überschriften",
    "settingsHeading": "Überschrift",
    "settingsHeading1": "Überschrift 1",
    "settingsHeading2": "Überschrift 2",
    "settingsHeading3": "Überschrift 3",
    "settingsHeading4": "Überschrift 4",
    "settingsHeading5": "Überschrift 5",
    "settingsHeading6": "Überschrift 6",
    "settingsInline": "Zeichenformate",
    "settingsBold": "Fett",
    "settingsItalic": "Kursiv",
    "settingsUnderline": "Unterstrichen",
    "settingsStrikethrough": "Durchgestrichen",
    "settingsSuperscript": "Hochgestellt",
    "settingsSubscript": "Tiefgestellt",
    "settingsCode": "Code",
    "settingsListElement": "Listenelement",
    "settingsBlocks": "Absatzformate",
    "settingsParagraph": "Absatz",
    "settingsBlockquote": "Zitat",
    "settingsPre": "Maschinenschrift",
    "settingsAlign": "Ausrichtung",
    "settingsAlignLeft": "Linksbündig",
    "settingsAlignCenter": "Zentriert",
    "settingsAlignRight": "Rechtsbündig",
    "settingsAlignJustify": "Blocksatz",
    "tinyHelperIframeAriaText": "Editor"
}
