name: Build and Release

on:
  push:
    tags:
      - '*'  # Trigger only when a tag is pushed

jobs:
  build:
    env:
      ArchiveName: LongEssayAssessment_Release-
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Remove v prefix
        id: removev
        run: echo "::set-output name=ref_name::$(echo ${{ github.ref_name }} | perl -0777 -pe 's/^v//')"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Prepare application for packaging
        run: |
          mkdir -p build
          rsync -av --exclude='.github/' --exclude='.git/' ./ LongEssayAssessment/

      - name: Create ZIP package
        run: |
          zip -r ./${{ env.ArchiveName }}${{ steps.removev.outputs.ref_name }}.zip ./LongEssayAssessment
        shell: bash

      - name: Create TAR.GZ package
        run: |
          tar -czf ./${{ env.ArchiveName }}${{ steps.removev.outputs.ref_name }}.tar.gz ./LongEssayAssessment
        shell: bash

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          name: "Release ${{ steps.removev.outputs.ref_name }}"
          draft: false
          prerelease: false
          artifacts: "./${{ env.ArchiveName }}${{ steps.removev.outputs.ref_name }}.zip,./${{ env.ArchiveName }}${{ steps.removev.outputs.ref_name }}.tar.gz"
